### ISSUE TITLE
Feature request: Prevent side effects on `bulletTrain.init`

### ISSUE THREAD

**Issue by askielboe** [BulletTrainHQ/bullet-train-js-client#16]
We use this library in a react native app and wrap the `onChange` callback in an event channel using redux saga. Since we only subscribe to channel updates after initialization it would be great if there was an option to prevent API calls during `bulletTrain` initialization (as to not waste our paid API calls).

Currently we use a workaround setting `disableCache: true` as this will stop `getFlags` from being called on init, but this feels like sort of a hack.

Having an explicit way to call `bulletTrain.init` without side effects would be great! 🙏🏼

**Comment by kyle-ssg** [comment]
Ok yep, makes sense, will add this later today.

**Comment by kyle-ssg** [comment]
Apologies for the delay!

Added **preventFetch** option to init as of **0.83** of bullet-train-client and react-native-bullet-train
