### ISSUE TITLE
api is undefined when setTrait or setTraits is called before init

### ISSUE THREAD

**Issue by davidskaarup** [BulletTrainHQ/bullet-train-js-client#24]
When trying to call `setTrait` or `setTraits` before `init` then `api` is undefined because the default value is only set during init.

```
 init({
  environmentID,
  api = defaultAPI,
  onChange,
  ...
```

```
setTrait = (key, trait_value) => {
  const { getJSON, identity, api } = this; <-- api is undefined before init
  ...
```

I don't think `setTrait` and `setTraits` is supposed to call the bullettrain api if it has not been initialized, instead only set the traits in state.

**Comment by kyle-ssg** [comment]
Hey @davidskaarup, thanks this makes sense. Correct the API would need to be initialised first, I'll add in error handling for this.

In the meantime if feasible you should be able to initialise first with preventFetch:true

**Comment by kyle-ssg** [comment]
As of version 0.2.1, calling setTrait/Traits before init will throw an error. If people have a scenario where they wish to do this, calling init with prevent fetch in combination with getFlags / identify should compensate.
