### ISSUE TITLE
Add type definitions for the client

### ISSUE THREAD

**Issue by kyle-ssg** [BulletTrainHQ/bullet-train-js-client#26]
Given the popularity of TypeScript, it would be good to add type definitions.

**Comment by kyle-ssg** [comment]
Added in bullet-train-client and react-native-bullet-train 0.2.3, enjoy!

**Comment by crutchcorn** [comment]
I'm getting a build failure when using TS as-of version `0.2.3` in Angular. 

```
7016: Could not find a declaration file for module 'bullet-train-client'. '/Users/crutchcorn/git/Coopervision/CVExtreme/node_modules/bullet-train-client/index.js' implicitly has an 'any' type.
  Try `npm install @types/bullet-train-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'bullet-train-client';`

2 import bulletTrain from 'bullet-train-client';
                          ~~~~~~~~~~~~~~~~~~~~~
```

However, renaming the `bullet-train-client.d.ts` file to `index.d.ts` in `node_modules` fixes this for me

**Comment by crutchcorn** [comment]
Another fix for this would be to add the following to `package.json`:

```
  "types": "./bullet-train-client.d.ts"
```

However, I think that the `isomorphic` import would also break. I would suggest moving both `d.ts` files into the same `index.d.ts` file (since they're namespaced, it should work properly) and then adding it to the `types` field in `package.json`

**Comment by kyle-ssg** [comment]
Ah strange, but I totally see what you mean about combining. I think ideally I'd look to also have some automated webpack approach for this since react-native, isomorphic AND the general lib have the same types.

If you're offering to do that quickly @crutchcorn that would definitely be appreciated!

**Comment by crutchcorn** [comment]
Yup! It's somewhat blocking stuff at work, so let me see if I can't just fix this issue quickly :) Forking now!

**Comment by kyle-ssg** [comment]
Thanks, apologies about that! It's strange because running the client locally command clicking jumps to the .d.ts instead of the lib code which signifies it's working.

Regardless, I'll keep an eye out for this, do some quick sanity checks and publish a version as soon as I see it!

**Comment by crutchcorn** [comment]
Right! Very weird, the differences between the TS language provider (for IDEs) and the compiler 🤷‍♂️

Either way #31 has been opened to help resolve this

**Comment by crutchcorn** [comment]
Also, instead of having a webpack fix, what I might suggest is doing something like:

`shared_types.ts`:
 
```typescript
export interface Test {
    example: string;
}
```

Then, in each of the instances you need those types:

```typescript
export * from './shared_types;
```

That way, you can have a single source-of-truth without having to deal with webpack copy messiness

**Comment by kyle-ssg** [comment]
Version @0.2.4 released, thank you again!

Will close for now, but reopen if you come across anything TS related.
