### ISSUE TITLE
bulletTrain.segment is throwing an error.

### ISSUE THREAD

**Issue by lomse** [BulletTrainHQ/bullet-train-js-client#30]
I'm using React **v16.12.0**

When I use `bulletTrain.segment`, I get the error below:
```bullet_train_client__WEBPACK_IMPORTED_MODULE_1___default.a.segment```

**Full Code**
```

const environmentID='dfsssffsdsfsfsdsdsggdsfs';

export const useBulletTrain = () => {
  const [hasLoaded, setHasLoaded] = useState(false);
  const [enableTimeAttendance, setEnableTimeAttendance] = useState(false);
  const [belongsToTrailUsers, setBelongToTrialUsers] = useState(false);
  
  useEffect(() => {

    bulletTrain.identify('yhjgjgjhgjgjgjg');
    bulletTrain.init({
      environmentID,
      defaultFlags: {
        enable_time_attendance: false
      },
      onChange: () => {
        try {
          bulletTrain.segment("trial_users");
        } catch (error) {
          console.log({error}) // error caught here 
        }

        setHasLoaded(true);
        setEnableTimeAttendance(bulletTrain.hasFeature("enable_time_attendance"));
        setBelongToTrialUsers(bulletTrain.segment("trial_users"));
      }
    });
  }, []);

  return { hasLoaded, enableTimeAttendance, belongsToTrailUsers };
};
```

**Comment by kyle-ssg** [comment]
bulletTrain.segment is not a function that we have, what are you trying to achieve?

**Comment by kyle-ssg** [comment]
You cannot get whether a user belongs to a segment directly, we may allow such things in the future but that is perhaps a misuse of the library.

The idea of segments is to control feature flags with segment overrides.

For your scenario of "trial users" you have 2 options:

Option 1: use setTrait and getTrait to detect and set whether the user is a "trial user".

Although this approach is simple it may not give you the most flexibility.


Option 2: Create a feature called "trial_user" and override it for a segment.


I'll explain with some screenshots here to give you a better idea of how this would work:


Step 1 : Create your feature flag for trial users, using whatever default you feel is best for on or off

![image](https://user-images.githubusercontent.com/8608314/90343326-601b0d80-e007-11ea-952c-9319e6d25163.png)

Step 2: Create a segment that drives the feature flag

![image](https://user-images.githubusercontent.com/8608314/90343364-ac664d80-e007-11ea-93ae-d81d86c9bd38.png)

Step 3: Set the feature flag to be turned on for that segment 

![image](https://user-images.githubusercontent.com/8608314/90343379-c99b1c00-e007-11ea-8bfd-e5042d5d25a6.png)


Your code would then be driven by ``bulletTrain.hasFeature``. You'd also get the additional benefit of being able to override this feature on a per user basis / add other segments that have this feature enabled e.g by an email address regex.

**Comment by kyle-ssg** [comment]
Hopefully this answers your question! If not feel free to reply and I'll get back to you.

**Comment by lomse** [comment]
Hi @kyle-ssg, thanks for suggesting this approach. Works great.
