### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by cuongqle** [BulletTrainHQ/bullet-train-js-client#36]
Hello,

I am getting this CORS issue, not happen to all users, just to some my users.

'https://api.bullet-train.io/api/v1/traits/' from origin 'https://mywebsite.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Could anyone has experienced on this, or how to configure the request header to pass to bullet to overcome this CORS issue?

Thanks/Cuong

**Comment by dabeeeenster** [comment]
Hi,

We would need more details on your integration. Can you confirm this is running against the hosted api at api.bullet-train.io?

Can you provide as much info as possible, including browser console logs etc?

**Comment by cuongqle** [comment]
Yes, my project is running against app.bullet-train.io

I am actually have not much information, but /identify endpoint seem does not get response, and i only able to see CORS error in the console. Seem /identify request has been rejected for that user, not too sure what exactly reason here?

Any provide is really appropriately!
Thanks/Cuong

**Comment by dabeeeenster** [comment]
We'd need to see explicit code and logs to be able to help I'm afraid.

**Comment by cuongqle** [comment]
Here are code what i have setup in my project, it written in typescript:

import bulletTrain from "bullet-train-client";

I have wrapped under my static method to catch exception from bullet to see what is exactly error has been throwed.

static identify(id) {
    try {
      bulletTrain.identify(id);
    } catch (e) {
      console.error('Error identifying: ', e); <==== this never reached
    }
  }

The above call send user Id, to ask bullet identify user, and if successed, user info (id / email) will be persisted into bullet.
But as far as i noticed, identify method has been rejected and the error catch never been reached, 

I only noticed in console this error:
'https://api.bullet-train.io/api/v1/traits/' from origin 'https://mywebsite' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 


Which more info you need, just let me know?

Thanks/Cuong

**Comment by dabeeeenster** [comment]
Does this happen every time you make the call?

**Comment by cuongqle** [comment]
Yes, it happen every time.

**Comment by dabeeeenster** [comment]
Are you able to email support@bullet-train.io with details of the Environment API key etc and ideally a small piece of code that can be run by itself that reproduces this?

**Comment by kyle-ssg** [comment]
Additionally to this, it would be worth checking what ID identify is being called with, it could be that unsafe url characters are causing this.

**Comment by dabeeeenster** [comment]
Are you able to find the request object in the Chrome developer tools network tab, then right click and copy as cURL, then try and run it as a cURL request. Does that work or fail?
